{
 "ETag": "W/\"1186e361ca645fa14972472080fdbfe30cca99dff660c626aef1b74d50f2f10a\"",
 "Last-Modified": "Fri, 24 Nov 2023 18:48:52 GMT",
 "base": {
  "repo": {
   "name": "pyerrors-feedstock"
  }
 },
 "closed_at": "2023-11-24T18:48:52Z",
 "created_at": "2023-11-24T18:44:27Z",
 "draft": false,
 "head": {
  "ref": "this_is_not_a_branch"
 },
 "html_url": "https://github.com/conda-forge/pyerrors-feedstock/pull/11",
 "id": 1616137552,
 "labels": [],
 "mergeable": null,
 "mergeable_state": "unknown",
 "merged": true,
 "merged_at": "2023-11-24T18:48:52Z",
 "number": 11,
 "state": "closed",
 "updated_at": "2023-11-24T18:48:52Z"
}