{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "1.1.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/1222368331.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python311"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.01.30.13.41.09",
 "pre_pr_migrator_attempts": {
  "python312": 47,
  "version": 124
 },
 "pre_pr_migrator_status": {
  "python312": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7042470607'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                win_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 pyro-ppl >=1.4.0  is not installable because there are no viable options\n\u2502  \u251C\u2500 pyro-ppl 1.5.2 would require\n\u2502  \u2502  \u2514\u2500 pytorch >=1.6,<1.8 , which does not exist (perhaps a missing channel);\n\u2502  \u251C\u2500 pyro-ppl [1.6.0|1.7.0] would require\n\u2502  \u2502  \u2514\u2500 pytorch >=1.8 , which does not exist (perhaps a missing channel);\n\u2502  \u251C\u2500 pyro-ppl [1.7.0|1.8.0] would require\n\u2502  \u2502  \u2514\u2500 pytorch >=1.9 , which does not exist (perhaps a missing channel);\n\u2502  \u2514\u2500 pyro-ppl [1.8.1|1.8.2|1.8.3|1.8.4|1.8.6] would require\n\u2502     \u2514\u2500 pytorch >=1.11 , which does not exist (perhaps a missing channel);\n\u2514\u2500 pytorch >=1.11.0  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "version": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3826725396\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1166, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 279, in run\n    eval_cmd(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 340, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 460, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
 },
 "smithy_version": "3.22.1"
}